IDIR=inc
SDIR=src
TDIR=test

CXX=g++
CFLAGS=-c -Wall -std=c++20
LFLAGS=-o
SRC=$(SDIR)/message.cpp $(SDIR)/messageFactory.cpp $(TDIR)/message-test.cpp
OBJ=message.o messageFactory.o message-test.o
EXEC=message-test
INC=-I /usr/include/ -I $(IDIR)
LIB=-lgtest -L /usr/lib64/
RM=rm -rf

all:
	$(CXX) $(CFLAGS) $(SRC) $(INC)
	$(CXX) $(OBJ) $(LFLAGS) $(EXEC) $(LIB)

clean:
	$(RM) $(OBJ) $(EXEC)

